apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ecobot-telegram
  name: ecobot-telegram
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecobot-telegram
  template:
    metadata:
      labels:
        app: ecobot-telegram
    spec:
      containers:
      - image: nginx
        name: ecobot-telegram
        imagePullPolicy: Always
        env:
        - name: AWS_KEY
          valueFrom:
            secretKeyRef:
              name: bot-secrets
              key: AWS_KEY
              optional: false # same as default; "mysecret" must exist
        - name: AWS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: bot-secrets
              key: AWS_KEY_ID
              optional: false # same as default; "mysecret" must exist
        - name: NOTION_API_KEY
          valueFrom:
            secretKeyRef:
              name: bot-secrets
              key: NOTION_API_KEY
              optional: false # same as default; "mysecret" must exist
        - name: NOTION_DATABASE
          valueFrom:
            secretKeyRef:
              name: bot-secrets
              key: NOTION_DATABASE
              optional: false # same as default; "mysecret" must exist
        - name: S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: bot-secrets
              key: S3_BUCKET
              optional: false # same as default; "mysecret" must exist
        - name: TELEGRAM_TOKEN
          valueFrom:
            secretKeyRef:
              name: bot-secrets
              key: TELEGRAM_TOKEN
              optional: false # same as default; "mysecret" must exist
        