apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ecobot-telegram
  name: ecobot-telegram
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: ecobot-telegram
  template:
    metadata:
      labels:
        app: ecobot-telegram
    spec:
      volumes:
      - name: s3-volume
        persistentVolumeClaim:
          claimName: csi-s3-pvc-dev
          readOnly: false
      - name: tmpfs-volume
        emptyDir:
          medium: Memory
      containers:
      - image: cr.yandex/crp5greagvr5ibj796uu/ecobot/telegram-bot
        name: ecobot-telegram
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /data/dynamic
          name: s3-volume
        - mountPath: /data/tmpfs
          name: tmpfs-volume
        env:
        - name: AWS_KEY
          valueFrom:
            secretKeyRef:
              name: bot-secrets
              key: AWS_KEY
              optional: false # same as default; "mysecret" must exist
        - name: AWS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: bot-secrets
              key: AWS_KEY_ID
              optional: false # same as default; "mysecret" must exist
        - name: NOTION_API_KEY
          valueFrom:
            secretKeyRef:
              name: bot-secrets
              key: NOTION_API_KEY
              optional: false # same as default; "mysecret" must exist
        - name: TRASH_DB_ID
          valueFrom:
            secretKeyRef:
              name: bot-secrets
              key: TRASH_DB_ID
              optional: false # same as default; "mysecret" must exist
        - name: URN_DB_ID
          valueFrom:
            secretKeyRef:
              name: bot-secrets
              key: URN_DB_ID
              optional: false # same as default; "mysecret" must exist
        - name: S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: bot-secrets
              key: S3_BUCKET
              optional: false # same as default; "mysecret" must exist
        - name: TELEGRAM_TOKEN
          valueFrom:
            secretKeyRef:
              name: bot-secrets
              key: TELEGRAM_TOKEN
              optional: false # same as default; "mysecret" must exist
        - name: DATA_PATH_PREFIX
          value: "/data"
        
        