apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: notion-api-key
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: bot-secrets # the target k8s secret name
  data:
  - secretKey: NOTION_API_KEY # the target k8s secret key
    remoteRef:
      key: e6qvjckb1d5sfcnab95e # ID of lockbox-secret
      property: NOTION_API_KEY
  - secretKey: S3_BUCKET # the target k8s secret key
    remoteRef:
      key: e6qvjckb1d5sfcnab95e # ID of lockbox-secret
      property: S3_BUCKET
  - secretKey: TELEGRAM_TOKEN # the target k8s secret key
    remoteRef:
      key: e6qvjckb1d5sfcnab95e # ID of lockbox-secret
      property: TELEGRAM_TOKEN
  - secretKey: AWS_KEY # the target k8s secret key
    remoteRef:
      key: e6qvjckb1d5sfcnab95e # ID of lockbox-secret
      property: AWS_KEY
  - secretKey: AWS_KEY_ID # the target k8s secret key
    remoteRef:
      key: e6qvjckb1d5sfcnab95e # ID of lockbox-secret
      property: AWS_KEY_ID
  - secretKey: NOTION_DATABASE # the target k8s secret key
    remoteRef:
      key: e6qvjckb1d5sfcnab95e # ID of lockbox-secret
      property: NOTION_DATABASE
  